services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: buyshap25
      POSTGRES_DB: grocery_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:buyshap25@db:5432/grocery_db
      PYTHONPATH: /code
    depends_on:
      - db
    volumes:
      - ./backend:/code

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

volumes:
  pgdata:

